services:
  db:
    image: postgres:16
    container_name: inventory-service-default
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: default
    volumes:
      - ./.postgres:/var/lib/postgresql/data

