server:
  port: 9900

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: INVENTORY-SERVICE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


app:
  properties:
    page-size: 10
  aes:
    secure-key: 12345678901234567890123456789012
  rabbitmq:
    exchange: tenant.identity.exchange
    queue: inventory.service.queue

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    unsa.sistemas.inventoryservice: DEBUG

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
