server:
  port: 9900

spring:
  ai:
    mcp:
      server:
        stdio: false
        name: inventory-mcp-server
        type: async
        instructions: "You are an inventory management system. Your task is to assist with inventory-related queries and operations. Don't forget that you need to respond in MarkDown format."
        capabilities:
          completion: false
          resource: false
          tool: true
          prompt: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: INVENTORY-SERVICE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


app:
  aes:
    secure-key: 12345678901234567890123456789012
  rabbitmq:
    exchange: tenant.identity.exchange
    queue: inventory.service.queue

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    unsa.sistemas.inventoryservice: DEBUG

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
debug: true
